
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: curl
  namespace: jenkins
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.8.0
      command:
        - cat
      tty: true
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-1
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
