
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: curl
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  containers:
    - name: curl
      image: bitnami/kubectl:latest
      command: [ "/bin/sh", "-ce" ]
      args:
        - | 
          
          apk update && apk add --no-cache curl || true
          tail -f /dev/null
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-1
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
  volumes:
    - emptyDir:
        medium: ""
      name: "workspace-volume"