
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: helm
spec:
  containers:
    - name: helm
      image: alpine/helm:3.14.4
      command:
        - cat
      tty: true
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-1
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
