
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: python
  namespace: jenkins
spec:
  containers:
    - name: python
      image: python:3.9
      command:
        - cat
      tty: true
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-1
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
