{
 "title": "flask_app",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "app_requests_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_requests_total{job=\"flask-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Start time",
   "type": "timeseries",
   "description": "process_start_time_seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"flask-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage ",
   "type": "timeseries",
   "description": "(rate)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{\"rate(process_cpu_seconds_total[1m])\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage ",
   "type": "timeseries",
   "description": "process_resident_memory_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"flask-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}