apiVersion: v1
data:
  alert-rules.yaml: |2
        # Группа правил для мониторинга узлов
        groups:
          - name: node-alerts
            rules:
              # Правило для высокой загрузки CPU
              - alert: HighCpuUsage
                expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
                for: 5m # Оповещение сработает, если условие истинно в течение 5 минут
                labels:
                  severity: warning
                annotations:
                  summary: "Высокая загрузка CPU на узле {{ $labels.instance }}"
                  description: "CPU узла {{ $labels.instance }} используется на {{ $value | humanizePercentage }}."

              # Правило для низкой доступной памяти
              - alert: LowMemoryAvailable
                expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100) < 20
                for: 5m # Оповещение сработает, если условие истинно в течение 5 минут
                labels:
                  severity: critical
                annotations:
                  summary: "Низкий объем доступной памяти на узле {{ $labels.instance }}"
                  description: "На узле {{ $labels.instance }} доступно только {{ $value | humanizePercentage }} памяти."

              # Правило для высокого использования диска (пример, можно настроить)
              - alert: HighDiskUsage
                expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
                for: 5m
                labels:
                  severity: warning
                annotations:
                  summary: "Высокое использование диска на узле {{ $labels.instance }} ({{ $labels.mountpoint }})"
                  description: "Диск на узле {{ $labels.instance }} ({{ $labels.mountpoint }}) используется на {{ $value | humanizePercentage }}."
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-alert-rules
  namespace: monitoring
