sonar.organization=zlocontrol
sonar.projectKey=zlocontrol_rsschool-devops-course-tasks
sonar.projectName=rsschool-devops-course-tasks
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
