apiVersion: v1
data:
  prometheus.yaml: |
    global:
      external_labels:
        monitor: prometheus
    scrape_configs:
      # ... (ваши scrape_configs здесь) ...
      - job_name: flask-app
        metrics_path: /metrics
        static_configs:
        - targets:
          - flask-app-release.jenkins.svc.cluster.local:8080
      - job_name: kube-state-metrics
        metrics_path: /metrics
        static_configs:
        - targets:
          - kube-state-metrics.monitoring.svc.cluster.local:8080
      - job_name: node-exporter
        metrics_path: /metrics
        static_configs:
        - targets:
          - node-exporter.monitoring.svc.cluster.local:9100
    alerting:
      alertmanagers:
        - scheme: HTTP
          static_configs:
            - targets: [ "prometheus-alertmanager.monitoring.svc.cluster.local:80" ]
    rule_files:
      - rules.yaml # <-- Prometheus ищет этот файл


  rules.yaml: |
    groups:
      - name: node-and-app-alerts
        rules:
          - alert: HighCpuUsage
            expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: " CPU  {{ $labels.instance }}"
              description: "CPU  {{ $labels.instance }} используется на {{ $value | humanizePercentage }}."

          # memory
          - alert: LowMemoryAvailable
            expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100) < 20
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "low of memory {{ $labels.instance }}"
              description: "На узле {{ $labels.instance }} доступно только {{ $value | humanizePercentage }} памяти."

          # data drive
          - alert: HighDiskUsage
            expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Higt drive {{ $labels.instance }} ({{ $labels.mountpoint }})"
              description: "Drive on node {{ $labels.instance }} ({{ $labels.mountpoint }}) используется на {{ $value | humanizePercentage }}."

          # request is Flask
          - alert: HighFlaskRequestRate
            expr: rate(http_requests_total{job="flask-app"}[1m]) > 10
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Flask({{ $labels.instance }})"
              description: "Flask- {{ $labels.instance }} получает {{ $value }} ."

kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring

  creationTimestamp: null
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: 3.5.0
    helm.sh/chart: prometheus-2.1.16
  name: prometheus-server
  namespace: monitoring
  resourceVersion: null
  uid: null