
    admin:
      user: "admin"
      password: "mySuperSecurePassword123"

    service:
      type: NodePort
      ports:
        grafana: 3000
      nodePorts:
        grafana: "30095"

    datasources:
      secretDefinition:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-server.monitoring.svc.cluster.local:9090
            isDefault: true

    persistence:
      enabled: false

    smtp:
      enabled: true
      host: smtp.example.com:587
      user: user@example.com
      password: password
      from_address: alerts@example.com
      skip_verify: true

    dashboardProviders:
      config: # <-- Убедитесь, что это 'config'
        default.yaml:
          apiVersion: 1
          providers:
            - name: default
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default

    dashboardsConfigMaps:
      - configMapName: grafana-flask-dashboard
        subPath: flask_app_dashboard.json # <-- ОБЯЗАТЕЛЬНО РАСКОММЕНТИРУЙТЕ ЭТО!
        # folderName: "Flask App" # Необязательно, но может помочь организовать
