#monitoring/grafana-values.yaml
admin:
  existingSecret: ""         # если используешь секрет — иначе задай ниже
  user: admin
  password: admin123         # не забудь заменить на что-то безопасное

service:
  type: NodePort
  port: 3000
  nodePort: 30080            # можешь изменить, если порт занят

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

persistence:
  enabled: false

smtp:
  enabled: true
  host: smtp.example.com:587
  user: user@example.com
  password: password
  from_address: alerts@example.com
  skip_verify: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

#dashboards:
#  default:
#    node-exporter-full:
#      json: |
#        ${JSON_СЮДА}   # Можно вставить экспорт из Grafana Web UI
