


admin:
  existingSecret: grafana-admin-secret
  existingSecretUserKey: GF_SECURITY_ADMIN_USER
  existingSecretPasswordKey: GF_SECURITY_ADMIN_PASSWORD



# === grafana.ini ===
ini:
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
  smtp:
    enabled: true
    host: smtp.example.com:587
    user: user@example.com
    from_address: grafana@example.com
    from_name: Grafana
    passwordFromSecret: grafana-smtp-secret
    passwordSecretKey: smtp-password


grafana:
  extraVolumes:

    - name: grafana-dashboards-prov-config
      configMap:
        name: grafana-all-dashboards-configmap
        items:
          - key: dashboards.yaml
            path: dashboards.yaml

    - name: grafana-custom-dashboards-files
      configMap:
        name: grafana-all-dashboards-configmap
        items:
          - key: flask_app_dashboard.json
            path: flask_app_dashboard.json
          - key: kube_dashboard.json
            path: kube_dashboard.json


    - name: grafana-datasources-config
      secret:
        secretName: grafana-admin-secret
        items:
          - key: datasources.yaml
            path: datasources.yaml

  extraVolumeMounts:

    - name: grafana-dashboards-prov-config
      mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
      subPath: dashboards.yaml

    - name: grafana-custom-dashboards-files
      mountPath: /etc/grafana/provisioning/dashboards_from_configmap


    - name: grafana-datasources-config
      mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
      subPath: datasources.yaml


  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    allowPrivilegeEscalation: false

  podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
    runAsNonRoot: true



service:
  type: NodePort
  ports:
    grafana: 3000
  nodePorts:
    grafana: 30095


persistence:
  enabled: false