{
 "title": "flask_app",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "app_requests_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_requests_total{job=\"flask-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Start time",
   "type": "timeseries",
   "description": "process_start_time_seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"flask-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage ",
   "type": "timeseries",
   "description": "(rate)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{\"rate(process_cpu_seconds_total[1m])\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage ",
   "type": "timeseries",
   "description": "process_resident_memory_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"flask-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Kube",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{fstype=\"ext4\",mountpoint=\"/\"} - node_filesystem_avail_bytes{fstype=\"ext4\",mountpoint=\"/\"}) / node_filesystem_size_bytes{fstype=\"ext4\",mountpoint=\"/\"} * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{fstype=\"ext4\",mountpoint=\"/\"} - node_filesystem_avail_bytes{fstype=\"ext4\",mountpoint=\"/\"}) / node_filesystem_size_bytes{fstype=\"ext4\",mountpoint=\"/\"} * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " CPU usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate({\" CPU usage per pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node_memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (node_memory_MemAvailable_bytes) / avg by (instance) (node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod Running Fail",
   "type": "timeseries",
   "description": "kube-state-metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count by(namespace) (kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(namespace) (kube_pod_status_phase{pod=\"Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}