
alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePorts:
      http: "30093"

server:
  service:
    type: NodePort
    nodePorts:
      http: "30090"
  extraScrapeConfigsSecret: additional-scrape-configs

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
