
alertmanager:
  enabled: true
  service:
    type: NodePort
    port: 9093
    nodePort: 30093

server:
  service:
    type: NodePort
    ports:
      http: 9090
    nodePorts:
      http: "30090"

  extraScrapeConfigs:
    - job_name: 'flask-app'
      metrics_path: /metrics
      static_configs:
        - targets:
            - flask-app-release.jenkins.svc.cluster.local:8080

    - job_name: 'kube-state-metrics'
      metrics_path: /metrics
      static_configs:
        - targets:
            - kube-state-metrics.monitoring.svc.cluster.local:8080

    - job_name: 'node-exporter'
      metrics_path: /metrics
      static_configs:
        - targets:
            - node-exporter.monitoring.svc.cluster.local:9100










