

controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts

  serviceType: NodePort
  nodePort: 32005

  persistence:
    enabled: true
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 5Gi

  JCasC:
    enabled: true
    configScripts:
      my-jcasc: |
        jenkins:
        jobs:
          - script: >
              pipelineJob('hello-world') {
                definition {
                  cps {
                    script('''node { echo "Hello world" }''')
                  }
                }
              }
