controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts

  serviceType: NodePort
  nodePort: 32005

  persistence:
    enabled: true
    storageClass: "local-path"  # Для k3s с Local Path Provisioner
    accessMode: ReadWriteOnce
    size: 5Gi

  JCasC:
    enabled: true
    configScripts:
      my-jcasc: |
        # === ИСПРАВЛЕНО: Удален блок 'jenkins:' и 'systemMessage:' ===
        # Это устраняет конфликт с конфигурацией по умолчанию.
        # 'jobs:' теперь является ключом верхнего уровня в этом JCasC YAML.
        jobs:
          - script: >
              pipelineJob('hello-world') {
                definition {
                  cps {
                    script('''node { echo "Hello world" }''')
                  }
                }
              }
