#jenkins/values.yaml


controller:
  admin:
    username: admin
    password: mySuperSecurePassword123

  startupProbe:
    httpGet:
      path: "/login"
      port: http
    failureThreshold: 30
    periodSeconds: 10



  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts

  serviceAccount:
    create: false
    name: jenkins

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - docker-workflow
    - git
    - git-client
    - credentials
    - configuration-as-code
    - email-ext
    - mailer

  jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"


  serviceType: NodePort
  nodePort: 30080

  persistence:
    enabled: true
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 5Gi

  # Configuration as Code (JCasC)

  JCasC:
    enabled: true
    overwrite: true
    configScripts:
      sonar-token: |
        credentials:
          system:
            domainCredentials:
            - credentials:
              - string:
                  scope: GLOBAL
                  id: sonar-token-id
                  secret: "a390c70a3175877e3345d5839057375510aee9a6" # tempory
                  description: "SonarCloud token for pipeline"
        

      email-config: |
        unclassified:
          location:
            adminAddress: "admin@example.com"
          mailer:
            smtpHost: "smtp.gmail.com"
            smtpPort: "465"
            useSsl: true
            smtpAuthUsername: "your_test_email@gmail.com"
            smtpAuthPassword: "fake-password"