#jenkins/values.yaml
controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts


  serviceType: NodePort
  nodePort: 32005


  persistence:
    enabled: true
    storageClass: "local-path"  # Для k3s с Local Path Provisioner
    accessMode: ReadWriteOnce
    size: 5Gi

#  # Jenkins Configuration as Code (JCasC)
#  JCasC:
#    enabled: true
#    defaultConfig: |
#      jenkins:
#        systemMessage: "Configured via JCasC"
#        jobs:
#          - script: >
#              pipelineJob('hello-world') {
#                definition {
#                  cps {
#                    script('''node { echo "Hello world" }''')
#                  }
#                }
#              }
  # === ИСПРАВЛЕНО: Используем controller.casc.config для JCasC ===
  # Это стандартный путь для передачи JCasC конфигурации в Helm Chart Jenkins.
  casc:
    enabled: true
    config: |
      jenkins:
        systemMessage: "Configured via JCasC"
        jobs:
          - script: >
              pipelineJob('hello-world') {
                definition {
                  cps {
                    script('''node { echo "Hello world" }''')
                  }
                }
              }
