name: Terraform AWS Destroy

on:
  # Trigger on push to a specific branch pattern, e.g., 'destroy-infra/dev'
  push:
    branches:
      - 'destroy-infra'
  # Allow manual trigger to specify the environment
  workflow_dispatch:
    inputs:
      tf_env:
        description: 'Terraform environment to destroy (e.g., dev, prod)'
        required: true

permissions:
  id-token: write # Required for OIDC role assumption
  contents: read  # Required for checking out the code

env:
  TERRAFORM_VERSION: "1.6.6"
  AWS_REGION: "us-east-1"
  TF_ROOT: "./" # Root directory where your Terraform code resides

jobs:
  terraform-destroy:
    name: Terraform Destroy Environment
    runs-on: ubuntu-latest

    steps:
      - name: Determine TF_ENV
        id: tfenv
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "TF_ENV=${{ github.event.inputs.tf_env }}" >> $GITHUB_ENV
          else
            BRANCH="${GITHUB_REF##*/}"
            echo "TF_ENV=$BRANCH" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Export dynamic secrets
        env:
          TF_BUCKET_NAME_dev: ${{ secrets.TF_BUCKET_NAME_dev }}
          GH_ROLE_ARN_dev: ${{ secrets.GH_ROLE_ARN_dev }}
          TF_BUCKET_NAME_prod: ${{ secrets.TF_BUCKET_NAME_prod }}
          GH_ROLE_ARN_prod: ${{ secrets.GH_ROLE_ARN_prod }}
        run: |
          echo "Determining secrets for environment: $TF_ENV"
          
          bucket_secret_name="TF_BUCKET_NAME_${TF_ENV}"
          role_secret_name="GH_ROLE_ARN_${TF_ENV}"

          if [[ -z "${!bucket_secret_name}" ]]; then
            echo "::error::Secret ${bucket_secret_name} not found for environment ${TF_ENV}!"
            exit 1
          fi
          if [[ -z "${!role_secret_name}" ]]; then
            echo "::error::Secret ${role_secret_name} not found for environment ${TF_ENV}!"
            exit 1
          fi

          echo "TF_BUCKET_NAME=${!bucket_secret_name}" >> $GITHUB_ENV
          echo "GH_ROLE_ARN=${!role_secret_name}" >> $GITHUB_ENV
          echo "Successfully exported TF_BUCKET_NAME and GH_ROLE_ARN for $TF_ENV."

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.GH_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Generate backend.tf
        working-directory: ${{ env.TF_ROOT }}
        run: |
          echo "terraform {
            backend \"s3\" {
              bucket  = \"$TF_BUCKET_NAME\"
              key     = \"$TF_ENV/terraform.tfstate\"
              region  = \"$AWS_REGION\"
              encrypt = true
            }
          }" > backend.tf
          echo "Generated backend.tf for bucket: $TF_BUCKET_NAME and key: $TF_ENV/terraform.tfstate"

      - name: Check tfvars file exists
        working-directory: ${{ env.TF_ROOT }}
        run: |
          FILE="terraform.${TF_ENV}.tfvars"
          if [ ! -f "$FILE" ]; then
            echo "ERROR: Terraform variables file '$FILE' not found. Cannot destroy infrastructure without environment-specific variables."
            exit 1
          fi
          echo "Using tfvars file: $FILE"

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init

      - name: Terraform Plan (Destroy)
        working-directory: ${{ env.TF_ROOT }}
        run: terraform plan -destroy -no-color -input=false -out=tfplan-destroy -var-file="terraform.${TF_ENV}.tfvars"

      - name: Upload tfplan-destroy artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-destroy
          path: tfplan-destroy
          retention-days: 1

      - name: Terraform Destroy
        working-directory: ${{ env.TF_ROOT }}
        run: terraform apply -destroy -auto-approve tfplan-destroy
